project: 
  type: website
  output-dir: docs

website: 
  navbar:
    left: 
      - text: "About me"
        href: pg1.qmd
      - text: "Projects"
        href: pg2.qmd
      - text: "Internships and Courses"
        href: pg3.qmd
      - text: "A"
      - href: midproject.qmd
      - text: "Mid Project"
      - href: pg5.qmd
format: 
  html: 
    theme: cyborg
       