project:
  type: website
  title: "Final Project"
  
website:
  sidebar:
    style: "docked"
    search: false
    contents:
      - section: "Introduction"
        contents:
          - index.qmd
          - research.qmd
      - section: "2. Research"
        contents:
          - question1.qmd
          - question2.qmd
          - question3.qmd
      - section: "3. Group Members"
        contents:
          - bhuvan.qmd
          - saketh.qmd
          - varun.qmd

format:
  html:
    theme: cosmo
    css: styles.css
editor: visual

